name: golang-govulncheck-action

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null

jobs:
  on: [push]

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.21.6
           go-package: ./CobaAction